name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - name: Compute next tag
        id: compute_tag
        uses: craig-day/compute-tag@v14
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: patch
      - uses: microsoft/setup-msbuild@v1
      - name: build
        run: msbuild NoTraderProtection.csproj -property:Configuration=Release
      - name: package
        run: |
          mkdir NoTraderProtection
          cp ModFolder/* NoTraderProtection/
          cp bin/Release/NoTraderProtection.dll NoTraderProtection/
          zip -r NoTraderProtection-${{steps.compute_tag.outputs.next_tag}}.zip NoTraderProtection
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: ${{ steps.compute_tag.outputs.next_tag }}
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          generate_release_notes: true
          files: |
            NoTraderProtection-${{steps.compute_tag.outputs.next_tag}}.zip